version: '1.0'
stages:
  - checkout
  - package
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    repo: kangyeju/python-flask-sample-app
    revision: master
    stage: checkout
  MyAppDockerImage:
    title: Building Docker Image
    type: build
    stage: package
    image_name: my-app-image
    working_directory: ./
    tag: v1.0.0
    dockerfile: Dockerfile
  MyUnitTests:
    title: Running Unit tests
    image: my-app-image
    stage: test 
    commands: 
      - pip install pytest
      - pytest      
  MyPushStep:
    title: Pushing to Docker Registry
    type: push
    stage: upload
    tag: master
    candidate: my-app-image
    image_name: kangyeju/pythonflasksampleapp
    registry: test
      
